# Generated by Django 5.0.1 on 2024-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=40)),
                ('user_name', models.CharField(max_length=20)),
                ('user_Gender', models.CharField(max_length=3)),
                ('user_rrn1', models.IntegerField(max_length=20)),
                ('user_rrn2', models.IntegerField(max_length=20)),
                ('user_Email', models.CharField(max_length=60)),
                ('user_AddressNum', models.IntegerField(max_length=10)),
                ('user_Address_doro', models.CharField(max_length=200)),
                ('user_Address_jibun', models.CharField(max_length=200)),
                ('user_Address_detail', models.CharField(max_length=200)),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='imgfile')),
            ],
        ),
    ]
