# Generated by Django 5.0.1 on 2024-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_AddressNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_rrn1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_rrn2',
            field=models.IntegerField(),
        ),
    ]
