# Generated by Django 5.0.1 on 2024-01-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_user_user_addressnum_alter_user_user_rrn1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_Gender',
            new_name='user_gender',
        ),
    ]
