# Generated by Django 5.0.1 on 2024-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_user_gender_user_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=1)),
                ('user_rrn1', models.IntegerField()),
                ('user_rrn2', models.IntegerField()),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address_num', models.IntegerField(blank=True, null=True)),
                ('user_address_doro', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address_jibun', models.CharField(blank=True, max_length=100, null=True)),
                ('user_address_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('user_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
