# Generated by Django 5.0.1 on 2024-01-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_userinfo_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userimage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=255)),
                ('image_type', models.CharField(max_length=100)),
                ('image_data', models.BinaryField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'userimage',
                'managed': False,
            },
        ),
    ]
