# Generated by Django 5.0.1 on 2024-01-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_userimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cityweather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cityweather',
                'managed': False,
            },
        ),
    ]
